name: Lint

on: [push]
#  push:
#    paths:
#      - '*.py'

env:
  DAY_OF_WEEK: Monday

jobs:

  check_env:
    runs-on: ubuntu-latest
    steps:
      - name: "print day of the week"
        run: |
          export day='$DAY_OF_WEEK'
          echo $day
          export day2=$DAY_OF_WEEK
          echo $day2

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install flake8
        run: |
         export DAY_OF_WEEK=$DAY_OF_WEEK
         pip install tox
         tox
#      - name: Run flake8
#        uses: suo/flake8-github-action@releases/v1
#        with:
#          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
