name: PROD
on:
  push:
    branches: [ main ]
#     paths:
#       - 'composer/**'
#       - 'bigquery/**'
#       - 'dataflow/**'

#     types: [closed]

env:
  COMPOSER_BUCKET: gs://us-central1-analytics-compo-ad2ccaf9-bucket
  STORAGE_PROJECT: analytics-plp-prod
  PR_BODY: ${{ github.event.pull_request.body }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.ANALYTICS_ADMIN_PROD_SA_JSON }}

jobs:

  deploy_into_gcp:
    runs-on: ['self-hosted', 'Linux', 'X64', 'pca-devops-prod']

    if: github.event.pull_request.merged == true

    steps:

    - name: Set up Python venv
      run: |
        python3 -m venv venv
