name: PROD
on:
  push:
    branches: [ main ]
#     paths:
#       - 'composer/**'
#       - 'bigquery/**'
#       - 'dataflow/**'

#     types: [closed]

jobs:

  deploy_into_gcp:
    runs-on: ubuntu-latest



    steps:

    - name: Set up Python venv
      run: |
        python3 -m venv venv
